import { Inter } from "next/font/google";
import "./globals.css";
import StoreContextMain from "./context/StoreContextMain";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MoveSeeks Flights",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <div className="fixed top-0 left-0 right-0 bg-white shadow text-black text-sm text-center h-5">
          **This site is not fully functional
        </div>
        <StoreContextMain>{children}</StoreContextMain>
      </body>
    </html>
  );
}
